key: value222
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  
 hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000 
